# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build bastardkb/skeletyl'
on:
  - workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      keyboard: '["bastardkb/skeletyl"]'
